### ISSUE TITLE
brotli default quality = 11, slow

### ISSUE THREAD

**Issue by wbcat** [Fishrock123/tide-compress#10]
Brotli uses 11 as default quality (brotli / enc / encode.rs BrotliEncoderInitParams)
This makes it very slow.

Is there a way to change this?

**Comment by Fishrock123** [comment]
Not at this time but I could add that easily enough. Do you have a suggestion for what the compression quality should be set to?

**Comment by wbcat** [comment]
According to this measurement by some google folks.
https://cran.r-project.org/web/packages/brotli/vignettes/brotli-2015-09-22.pdf

brotli:1 delivers about enough compression performance to saturate a 1 GBit Network Connection.

This seems to be a reasonable default for me.

An easy configuration option on top would be very convenient.

Would love to see this.

:-)

**Comment by Fishrock123** [comment]
`Config::brotli_quality` and `Config::defalte_quality` now exist in 0.11.

The default for Brotli has been set to `Fastest` (`1`).
