### ISSUE TITLE
v0.10.1: surf in build-depedencies brings in OpenSSL which complicates the build

### ISSUE THREAD

**Issue by ttiurani** [Fishrock123/tide-compress#7]
Unfortunately I ran into a somewhat esoteric problem. This commit:

https://github.com/Fishrock123/tide-compress/commit/61f8b84e4d0f7c879ecbe919bc3c76deea9e9c65

brought with it `build-dependencies` which includes `surf`, which in turn brings in `curl-client` which has `openssl-probe` and `openssl-sys` deps. My Bazel build is cross-compiling to Raspberry Pi 3B, and I don't have OpenSSL in that buildroot, which causes the entire build to fail with "Could not find directory of OpenSSL installation".

Might it be possible to use in the `build.rs` a web client that uses rustls, so that building tide-compress wouldn't require an existing OpenSSL installation?

**Comment by Fishrock123** [comment]
ah. heh. ok I had a weird suspicion this `build.rs` could cause trouble. I'll try to resolve it in the deps and cargo config but if that doesn't work we can always do in-repo codegen instead of at-build.

**Comment by Fishrock123** [comment]
@ttiurani can you see if [0.10.2](https://github.com/Fishrock123/tide-compress/releases/tag/0.10.2) works for you?

**Comment by ttiurani** [comment]
Much better, worked great! Thank you for the quick fix.

p.s. Btw, tide-acme relies on tide-rustls, which means the whole tide ecosystem doesn't have OpenSSL as a dep, so great that tide-compress doesn't have it either :)
